#!/bin/bash

if [ -f /sys/devices/pci0000\:00/0000\:00\:03.0/0000\:03\:00.0/remove ]
then
	echo 1 > /sys/devices/pci0000\:00/0000\:00\:03.0/0000\:03\:00.0/remove
fi

if [ -f /sys/bus/pci/devices/0000\:04\:00.0/remove ]
then
	echo 1 > /sys/bus/pci/devices/0000\:04\:00.0/remove
fi

if [ -f /sys/bus/pci/devices/0000\:82\:00.0/remove ]
then
	echo 1 > /sys/bus/pci/devices/0000\:82\:00.0/remove
fi

if [ -f /sys/bus/pci/devices/0000\:84\:00.0/remove ]
then
	echo 1 > /sys/bus/pci/devices/0000\:84\:00.0/remove
fi

if [ -f /sys/bus/pci/devices/0000\:85\:00.0/remove ]
then
	echo 1 > /sys/bus/pci/devices/0000\:85\:00.0/remove
fi

echo 1 > /sys/bus/pci/rescan
