//
// rorc_registers.h: RORC Register Definitions
//
// Note:
// This file was automatically generated from:
// src/packages/rorc_config.vhd
// hash: 0c4d5bc379474d613235257607c2fc565bf706de
// short hash: 0c4d5bc
//

#define RORC_REVISION 0x0c4d5bc
#define RORC_BUILD_DATE 0x20130729

#define RORC_CHANNEL_OFFSET 0x00008000
#define RORC_REG_FIRMWARE_REVISION 0
#define RORC_REG_FIRMWARE_DATE 1
#define RORC_REG_FPGA_TEMPERATURE 2
#define RORC_REG_FPGA_VCCINT 3
#define RORC_REG_FPGA_VCCAUX 4
#define RORC_REG_SC_REQ_CANCELED 5
#define RORC_REG_QSFP_CTRL 6
#define RORC_REG_DMA_TX_TIMEOUT 10
#define RORC_REG_I2C_CONFIG 11
#define RORC_REG_I2C_OPERATION 12
#define RORC_REG_ILLEGAL_REQ 14
#define RORC_REG_MULTIDWREAD 15
#define RORC_REG_PCIE_CTRL 16
#define RORC_REG_TYPE_CHANNELS 17
#define RORC_REG_PCIE_DST_BUSY 18
#define RORC_REG_UC_CTRL 19
#define RORC_REG_FAN_CTRL 20
#define RORC_REG_PCIE_TERR_DROP 21
#define RORC_REG_UC_SPI_DATA 22
#define RORC_REG_UC_SPI_CTRL 23
#define RORC_REG_EBDM_N_SG_CONFIG 0
#define RORC_REG_EBDM_BUFFER_SIZE_L 1
#define RORC_REG_EBDM_BUFFER_SIZE_H 2
#define RORC_REG_RBDM_N_SG_CONFIG 3
#define RORC_REG_RBDM_BUFFER_SIZE_L 4
#define RORC_REG_RBDM_BUFFER_SIZE_H 5
#define RORC_REG_EBDM_SW_READ_POINTER_L 6
#define RORC_REG_EBDM_SW_READ_POINTER_H 7
#define RORC_REG_RBDM_SW_READ_POINTER_L 8
#define RORC_REG_RBDM_SW_READ_POINTER_H 9
#define RORC_REG_DMA_CTRL 10
#define RORC_REG_DMA_N_EVENTS_PROCESSED 11
#define RORC_REG_EBDM_FPGA_WRITE_POINTER_H 12
#define RORC_REG_EBDM_FPGA_WRITE_POINTER_L 13
#define RORC_REG_RBDM_FPGA_WRITE_POINTER_L 14
#define RORC_REG_RBDM_FPGA_WRITE_POINTER_H 15
#define RORC_REG_SGENTRY_ADDR_LOW 16
#define RORC_REG_SGENTRY_ADDR_HIGH 17
#define RORC_REG_SGENTRY_LEN 18
#define RORC_REG_SGENTRY_CTRL 19
#define RORC_REG_DMA_STALL_CNT 20
#define RORC_REG_GTX_ASYNC_CFG 21
#define RORC_REG_DMA_ELFIFO 22
#define RORC_REG_DMA_PKT_SIZE 23
#define RORC_REG_GTX_DRP_CTRL 24
#define RORC_REG_GTX_CTRL 0
#define RORC_REG_GTX_RXDFE 1
#define RORC_REG_GTX_DISPERR_CNT 2
#define RORC_REG_GTX_RXNIT_CNT 3
#define RORC_REG_GTX_RXLOS_CNT 4
#define RORC_REG_GTX_RXBYTEREALIGN_CNT 5
#define RORC_REG_DDL_CTRL 8
#define RORC_REG_DDL_PG_EVENT_LENGTH 9
#define RORC_REG_DDL_PG_PATTERN 10
#define RORC_REG_DDL_PG_NUM_EVENTS 11
#define RORC_REG_DDL_PG_WAIT_TIME 12
#define RORC_REG_DDL_CMD 13
#define RORC_REG_DDL_CLR_EL 14
#define RORC_REG_DDL_CONFIG 15
#define RORC_REG_DDL_EC 16
#define RORC_REG_DDL_DEADTIME 17
#define RORC_REG_DDL_CTSTW 18
#define RORC_REG_DDL_FESTW 19
#define RORC_REG_DDL_DTSTW 20
#define RORC_REG_DDL_IFSTW 21
#define RORC_DMA_CMP_SEL 13
